<?php
// get-gallery-images.php
// Returns cached list of image files from the gallery directory.
// Cache is generated by tools/generate-gallery-cache.php

header('Content-Type: application/json');

$cacheFile = 'data/gallery-cache.json';

// Try to load from cache first
if (file_exists($cacheFile)) {
    $images = json_decode(file_get_contents($cacheFile), true);
    echo json_encode($images ?: []);
    exit;
}

// Fallback: scan directory if cache doesn't exist
$galleryDir = 'gallery/';
$allowedExtensions = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
$images = [];

if (is_dir($galleryDir)) {
    $files = scandir($galleryDir);
    foreach ($files as $file) {
        $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
        if (in_array($ext, $allowedExtensions)) {
            $images[] = $galleryDir . $file;
        }
    }
}

sort($images);
echo json_encode($images);
?>
